apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-stress-test
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: jmeter
          image: ghcr.io/pewpewlab/jemter-k8s:latest
          env:
            - name: TEST_PLAN
              value: /tests/test.jmx
            - name: RESULTS_FILE
              value: /results/results.csv
            - name: LOG_FILE
              value: /results/jmeter.log
            - name: GENERATE_HTML_REPORT
              value: "true"
            - name: HTML_REPORT_DIR
              value: /results/html-report
          volumeMounts:
            - name: tests
              mountPath: /tests
            - name: results
              mountPath: /results
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      volumes:
        - name: tests
          configMap:
            name: jmeter-test-plan
        - name: results
          emptyDir: {}
